os:
  - linux
language: python
python:
  - "2.7"
  - "3.4"

sudo: true

before_install:
  # Install the CUDA toolkit
  - echo "Installing CUDA library"
#  - export CUDAVERSION=6.5-19
#  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDAVERSION}_amd64.deb
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_6.5-19_amd64.deb
#  - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_${CUDAVERSION}_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_6.5-19_amd64.deb
  - travis_retry sudo apt-get update -qq
#  - travis_retry sudo apt-get install -y cuda-drivers
  - travis_retry sudo apt-get install -y cuda
  - export CUDA_HOME=/usr/local/cuda-7.5
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64
  - PATH=${CUDA_HOME}/bin:${PATH}
  - export PATH


install:
  - "pip install --upgrade pip"
  - "pip install cython"
  - "pip install PyWavelets"
  - "python setup.py install --user"

# command to run tests
script:
  - "python test/test_all.py"
