os:
  - linux

language: python
python:
  - "2.7"
  - "3.4"

before_install:
  # for travis machines
  - sudo apt-get install -y nvidia-opencl-dev nvidia-compute-profiler
  - sudo apt-get install -y nvidia-cuda-toolkit
  - sudo apt-get install -y python-pywt

install:
  - "pip install --upgrade pip"
  - "pip install cython"
  - "pip install PyWavelets"
  - "python setup.py install --user"

# command to run tests
script:
  - "python test/test_all.py"
